Implemented currently needed effect classes
AlekseyPanas/CSC404_Magengaard pull request #70
Opened 2024-02-19 20:10 UTC by PyroPoro

2024-02-19 20:11 UTC, AlekseyPanas submitted a review, later dismissed
All good

2024-02-19 21:53 UTC, 1whatleytay requested changes

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public AEffect SetCollider(Collider col, ColliderType colliderType) {
All effects have a collider? I thought some of the reasons we wanted to make this effect system abstraction is so we didn't have to do this.

Like what if we have a Raycast spell? I don't think ways have a collider (I think?)

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
What's the point of `private set` if you're going to provide a setter? C#'s construction syntax should allow you.

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +public abstract class AEffect {
Not asking for a change here, more of a question. Why is this an abstract class again? I think properties are designed for uses in interfaces, and I don't think this is used in a unity property at this point.

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
Why do we have this enum out of curiosity? Couldn't we just find the type by doing `col is BoxCollider` or something?

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
Naming is strange here. Why is one `col` and the other one specifies `colliderType`. Use `col` or `collider`.

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/WaterEffect.cs
> +}
Can we use C#'s construction classes? Why have a private setter if you've exposed a setter method? Just do:
```suggestion
public class WaterEffect : AEffect {
    public float WaterDensity; // or { get; set; } 
}
```

Then construct with `new WaterEffect { WaterDensity = 5 }`.

2024-02-19 21:53 UTC, 1whatleytay commented on Assets/Scripts/Effects/WaterEffect.cs
> +}
Same with all the other effect classes. I saw the DamageEffect class in an earlier PR but I think I passed it due to pressure. C# has a system for this and I think we should use it unless there's a good reason not to.

2024-02-19 21:55 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public AEffect SetCollider(Collider col, ColliderType colliderType) {
Or is this supposed to be more `AAreaEffect` or something? If so we should change the name! If not, we should restrict IEffectListener to only allow for subclasses of `AEffect` (e.g. `interface IEffectListener<T> where T: AEffect` I believe).

2024-02-19 22:16 UTC, AlekseyPanas commented on Assets/Scripts/Effects/AEffect.cs
> +public abstract class AEffect {
Because the rule:
A "dog" is an "animal" so Animal is an abstract class
A "dog" can be fed food so its "feedable", which is an interface
In this case, the effect subclasses are "Effects", hence its an abstract class

2024-02-19 22:16 UTC, AlekseyPanas commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
cause cheaper to compare against enum

2024-02-19 22:17 UTC, AlekseyPanas commented on Assets/Scripts/Effects/WaterEffect.cs
> +}
Because we want this to be a builder pattern. The setters must return the object again

2024-02-19 22:17 UTC, AlekseyPanas commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
Builder pattern

2024-02-19 22:18 UTC, AlekseyPanas commented on Assets/Scripts/Effects/AEffect.cs
> +    public AEffect SetCollider(Collider col, ColliderType colliderType) {
No, Its an abstract class for ALL effects. So yes, we can restrict IEffectListener

2024-02-19 22:20 UTC, AlekseyPanas commented on Assets/Scripts/Effects/AEffect.cs
> +    public AEffect SetCollider(Collider col, ColliderType colliderType) {
The point of the collider is for the listener of the effect to always know the area where the effect is happening. This is often useful. We can add an extra option for setting the colliderType to some NONE option in case we dont want to pass a collider.

2024-02-19 23:31 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public AEffect SetCollider(Collider col, ColliderType colliderType) {
Not trying to push back but why is it useful? Does it need to know the origin?

> We can add an extra option for setting the colliderType to some NONE option in case we dont want to pass a collider.

Isn't this a code smell? Providing a field that won't be used in some subclasses (refactoring guru seems to call this "Refused Bequest" https://refactoring.guru/smells/refused-bequest). It just seems to interesting because now all effects will either be AOE or have to "disable" the AOE field. It's not the end of the world but it's just a really interesting design decision.

Because we're using IEffectListener and generics we don't even technically don't even need a parent class. Each effect can specify exactly what is needed, and the handler doesn't need to downcast or guess to get any properties.

2024-02-19 23:32 UTC, PyroPoro commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
fixed

2024-02-19 23:35 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +    public ColliderType colliderType {get; private set;}
Builder pattern seems to be made for two reasons:
- For objects that need a complicated initialization/use reflection/are generally expensive to make.
- For languages that have no nice way of constructing an object (e.g. `new XBuilder().setY().setZ().build()` is nicer than `X x = new X; x.y = set; x.z = set;`).

I don't think we fall under either of those cases. Our language provides an awesome way to do both, and all our effect classes might as well be `struct`s 😅 Is there a reason you're attached to this pattern?

2024-02-19 23:41 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +public abstract class AEffect {
I think that's more nomenclature than something you should use to decide. A dog is also a collection of cells so `CellCollection` is must be an abstract class. But then that means a dog can't be both an animal and a cell collection, or that all cell collections have to be an animal or that...

You should pick the construct that helps you best. Name your classes how you decide to use them, don't decide how to use your classes based on how you named them.

2024-02-19 23:43 UTC, 1whatleytay commented on Assets/Scripts/Effects/AEffect.cs
> +public abstract class AEffect {
That being said choose whatever you would like. I usually see projects starting with an interface and only using abstract classes when they are absolutely necessary (because of the restrictions they impose). This project seems to just jump to abstract classes, and that's just an interesting choice to me (seems like sometimes they are required!)

2024-02-19 23:50 UTC, 1whatleytay commented on Assets/Scripts/Effects/WaterEffect.cs
> +}
Why

2024-02-20 00:24 UTC, AlekseyPanas approved these changes

2024-02-20 00:24 UTC, 1whatleytay approved these changes

2024-02-20 00:29 UTC, merged