Add Ballon and Balloon Room
AlekseyPanas/CSC404_Magengaard pull request #91
Opened 2024-03-16 04:28 UTC by 1whatleytay

Add prefabs for the ballon and balloon room.

2024-03-16 21:16 UTC, AlekseyPanas requested changes
make balloon a network behavior, everything else is good

2024-03-16 21:16 UTC, AlekseyPanas commented on Assets/Prefabs/InteractableObjects/Balloon/Balloon.cs
> +public class Balloon : MonoBehaviour, IEffectListener<TemperatureEffect>
Should be NetworkBehavior. Logic only runs if on server (return if not IsServer)

2024-03-17 01:04 UTC, AlekseyPanas submitted a review, later dismissed

2024-03-17 02:01 UTC, AlekseyPanas approved these changes

2024-03-17 02:01 UTC, PyroPoro approved these changes

2024-03-17 02:03 UTC, merged